[project]
name = "flet-secure-storage"
version = "0.1.0"
description = "SecureStorage control for Flet"
authors = [{ name = "Flet contributors", email = "you@example.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flet",
]

[project.urls]
Homepage = "https://mydomain.dev"
Documentation = "https://github.com/MyGithubAccount/flet-secure-storage"
Repository = "https://github.com/MyGithubAccount/flet-secure-storage"
Issues = "https://github.com/MyGithubAccount/flet-secure-storage/issues"

[tool.setuptools.package-data]
"flutter.flet_secure_storage" = ["**/*"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
