[project]
name = "examples-gallery"
version = "0.1.0"
description = "Live demo of Flet examples."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Flet developer", email = "you@example.com" }
]
dependencies = [
    "flet==0.70.0.dev6833",
]

[tool.uv]
prerelease = "allow"

[tool.flet]
# Docs: https://flet.dev/docs/publish
org = "com.mycompany"
product = "Examples Gallery"
company = "Flet"
copyright = "Copyright (C) 2025 by Flet"

[tool.flet.app]
path = "src"

[tool.flet.web]
base_url = "apps/examples-gallery/dist"
renderer = "auto"
route_url_strategy = "hash"
