[tool.poetry]
name = "flet-pyodide"
version = "0.1.0"
description = "Flet for Pyodide - build standalone SPA in Python with Flutter UI."
authors = ["Appveyor Systems Inc. <hello@flet.dev>"]
license = "MIT"
readme = "README.md"

packages = [
    { include = "flet", from = "src" },
]

[tool.poetry.urls]
homepage = "https://flet.dev"
repository = "https://github.com/flet-dev/flet"
documentation = "https://flet.dev/docs"

[tool.poetry.dependencies]
flet-core = "0.1.0"
python = "^3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
float_to_top = true