name: flet
description: Write entire Flutter app in Python or add server-driven UI experience into existing Flutter app.
homepage: https://flet.dev
repository: https://github.com/flet-dev/flet/tree/main/packages/flet
version: 0.80.4

# Supported platforms
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  battery_plus: ^7.0.0
  collection: ^1.19.0
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.3.0
  equatable: ^2.0.3
  file_picker: 10.3.8
  flutter_highlight: ^0.7.0
  flutter_markdown: ^0.7.6+2
  flutter_svg: ^2.2.1
  highlight: ^0.7.0
  http: ^1.5.0
  markdown: ^7.3.0
  msgpack_dart: ^1.0.1
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  screenshot: ^3.0.0
  screen_brightness: ^2.1.7
  sensors_plus: ^7.0.0
  shared_preferences: ^2.5.3
  share_plus: ^12.0.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  vector_math: ^2.2.0
  web: ^1.1.1
  web_socket_channel: ^3.0.2
  window_manager: ^0.5.1
  window_to_front: ^0.0.3
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
