name: flet
description: Write entire Flutter app in Python or add server-driven UI experience into existing Flutter app.
homepage: https://flet.dev
repository: https://github.com/flet-dev/flet/packages/flet
version: 0.22.1

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  redux: ^5.0.0
  flutter_redux: ^0.10.0
  equatable: ^2.0.3
  web_socket_channel: ^2.4.0
  window_manager: ^0.3.7
  http: ^1.1.2
  collection: ^1.16.0
  url_launcher: ^6.1.5
  flutter_markdown: ^0.6.18+2
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  markdown: ^7.1.1
  file_picker: ^8.0.3
  shared_preferences: ^2.0.15
  flutter_svg: ^2.0.9
  window_to_front: ^0.0.3
  sensors_plus: ^4.0.2
  path: ^1.8.2
  js: ^0.6.5
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg