name: flet
description: Write entire Flutter app in Python or add server-driven UI experience into existing Flutter app.
homepage: https://flet.dev
repository: https://github.com/flet-dev/flet/packages/flet
version: 0.70.0

# Supported platforms
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.19.0
  device_info_plus: ^12.1.0
  equatable: ^2.0.3
  file_picker: ^10.3.3
  flutter_highlight: 0.7.0
  flutter_markdown: 0.7.6+2
  flutter_svg: 2.2.1
  highlight: ^0.7.0
  http: 1.5.0
  markdown: 7.3.0
  msgpack_dart: ^1.0.1
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  screenshot: ^3.0.0
  sensors_plus: ^6.1.1
  shared_preferences: 2.5.3
  shimmer: ^3.0.0
  url_launcher: 6.3.2
  vector_math: ^2.2.0
  web: ^1.1.1
  web_socket_channel: ^3.0.2
  window_manager: ^0.5.1
  window_to_front: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
