name: flet_code_editor
description: Flet CodeEditor control
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_code_editor: ^0.3.1
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0

  flet:
    path: ../../../../../../../packages/flet

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
