name: flet_geolocator
description: Flet Geolocator control
homepage: https://flet.dev
repository: https://github.com/flet-dev/flet/packages/flet_geolocator
version: 0.22.0

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.1

  flet:
    path: ../flet/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0