name: flet_camera
description: Flet Camera control
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.3
  image: ^4.5.4

  flet:
    path: ../../../../../../../packages/flet

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
