[project]
name = "flet-project"
version = "0.1.0"
description = ""
authors = [{name = "Appveyor Systems Inc.", email ="hello@flet.dev"}]
license = "Apache-2.0"
requires-python = ">=3.10,<3.14"
dependencies = [
    "flet",
    "flet-cli",
    "flet-desktop",
    "flet-web",
]

[tool.uv.sources]
flet = { workspace = true }
flet-cli = { workspace = true }
flet-desktop = { workspace = true }
flet-web = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[dependency-groups]
dev = [
    "pytest >=7.2.0",
    "tomlkit >=0.11.6",
    "cryptography >=39.0.0",
    "pyinstaller >=6.6.0",
    "pillow >=10.3.0",
    "pre-commit >=2.21.0",
    "pypi-cleanup==0.1.4",
    "matplotlib >=3.10.1",
    "plotly >=6.0.1",
    "pandas >=2.2.3",
    "ruff>=0.11.7",
]
docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings-python",
    "mkdocstrings-python-xref",
    "mike",
    "markdown>=3.6",
    "pymdown-extensions",
    "mkdocs-glightbox",
    "mkdocs-section-index",
    "griffe-modernized-annotations",
    "pygments>=2.16",
    "markdown-exec[ansi]",
]
all = [
    { include-group = 'dev' },
    { include-group = 'docs' },
]

[tool.ruff]
line-length = 88
target-version = "py39"
fix = true
show-fixes = true

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I"
]
preview = true
pydocstyle = { convention = 'google' }

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
