[tool.poetry]
name = "flet-project"
version = "0.1.0"
description = ""
authors = ["Appveyor Systems Inc. <hello@flet.dev>"]
license = "Apache-2.0"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9,<3.14"

[tool.poetry.group.dev.dependencies]
flet-cli = {path = "packages/flet-cli", develop = true}
flet-desktop = {path = "packages/flet-desktop", develop = true}
flet-web = {path = "packages/flet-web", develop = true}
flet = {path = "packages/flet", develop = true}
pytest = "^7.2.0"
black = "^22.12.0"
tomlkit = "^0.11.6"
cryptography = "^39.0.0"
pyinstaller = "^6.6.0"
pillow = "^10.3.0"
pre-commit = "^2.21.0"
hypercorn = "^0.14.4"
gunicorn = "^21.2.0"
pypi-cleanup = "0.1.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
