[tool.poetry]
name = "flet-project"
version = "0.1.0"
description = ""
authors = ["Appveyor Systems Inc. <hello@flet.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.group.dev.dependencies]
flet-core = {path = "packages/flet-core", develop = true}
flet = {path = "packages/flet", develop = true}
pytest = "^7.2.0"
black = "^22.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
