[project]
name = "flet-charts"
version = "0.1.0"
description = "Interactive chart controls for Flet apps."
readme = "README.md"
authors = [{ name = "Flet contributors", email = "hello@flet.dev" }]
license = "Apache-2.0"
requires-python = ">=3.10"
dependencies = [
    "flet",
]

[project.optional-dependencies]
all = ["matplotlib>=3.10.7", "plotly>=6.4.0", "kaleido>=1.2.0"]
plotly = ["plotly>=6.4.0", "kaleido>=1.2.0"]
matplotlib = ["matplotlib>=3.10.7"]

[project.urls]
Homepage = "https://flet.dev"
Documentation = "https://docs.flet.dev/charts"
Repository = "https://github.com/flet-dev/flet/tree/main/sdk/python/packages/flet-charts"
Issues = "https://github.com/flet-dev/flet/issues"

[tool.setuptools.package-data]
"flutter.flet_charts" = ["**/*"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
