name: flet_secure_storage
description: Flet Secure Storage control
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: 10.0.0

  flet:
    path: ../../../../../../../packages/flet

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
