name: flet_webview
description: Flet WebView control
homepage: https://flet.dev
repository: https://github.com/flet-dev/flet/packages/flet_webview
version: 0.24.1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  webview_flutter: ^4.9.0
  flutter_web_plugins:
    sdk: flutter
  webview_flutter_web: ^0.2.3+2
  webview_flutter_platform_interface: ^2.4.0
  abutil: ^0.1.2

  flet:
    path: ../flet/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0