name: flet_map
description: Flet Map control
homepage: https://flet.dev
repository: https://github.com/flet-dev/flet/packages/flet_map
version: 0.25.2

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  flutter_map: ^7.0.2
  flutter_map_animations: ^0.8.0
  flutter_map_cancellable_tile_provider: ^3.0.2
  latlong2: ^0.9.1

  flet:
    path: ../flet/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0