[project]
name = "flet"
version = "0.1.0"
description = "Flet for Python - easily build interactive multi-platform apps in Python"
authors = [{name = "Appveyor Systems Inc.", email = "hello@flet.dev"}]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flet-cli; extra == 'cli'",
    "flet-desktop; extra == 'desktop' and (platform_system == 'Darwin' or platform_system == 'Windows')",
    "flet-web; extra == 'web'",
    "oauthlib >=3.2.2; platform_system != 'Pyodide'",
    "httpx >=0.28.1; platform_system != 'Pyodide'",
    "repath >=0.9.0",
    "msgpack >=1.1.0",
    "typing-extensions; python_version < '3.11'"
]

[project.urls]
Homepage = "https://flet.dev"
Repository = "https://github.com/flet-dev/flet"
Documentation = "https://docs.flet.dev/"

[project.optional-dependencies]
all = ["flet-cli", "flet-desktop", "flet-web"]
cli = ["flet-cli"]
desktop = ["flet-desktop"]
web = ["flet-web"]

[project.scripts]
flet = "flet.cli:main"

[dependency-groups]
extensions = [
    "flet-ads",
    "flet-audio",
    "flet-audio-recorder",
    "flet-charts",
    "flet-datatable2",
    "flet-flashlight",
    "flet-geolocator",
    "flet-lottie",
    "flet-map",
    "flet-permission-handler",
    "flet-rive",
    "flet-video",
    "flet-webview",
]
test = [
    "pytest >=7.2.0",
    "pytest_asyncio >=1.1.0",
]
dev = [
    "tomlkit >=0.11.6",
    "cryptography >=39.0.0",
    "pillow >=10.3.0",
    "pre-commit >=2.21.0",
    "pypi-cleanup==0.1.4",
    "pandas >=2.2.3",
    "numpy >=2.2.0",
    "scikit-image >=0.25.2",
    "ruff >=0.13.1",
    { include-group = 'test' },
]
docs-coverage = [
    "docstr-coverage >=2.3.2",
]
docs = [
    "mkdocs >=1.6.1",
    "mkdocs-material >=9.6.20",
    "mkdocstrings-python >=1.18.2",
    "mkdocstrings-python-xref >=1.16.4",
    "mike >=2.1.3",
    "markdown >=3.9",
    "pymdown-extensions >=10.16.1",
    "mkdocs-exclude >=1.0.2",
    "mkdocs-glightbox >=0.5.1",
    "mkdocs-open-in-new-tab >=1.0.8",
    "mkdocs-section-index >=0.3.10",
    "griffe-modernized-annotations >=1.0.8",
    "griffe-warnings-deprecated >=1.1.0",
    "pygments >=2.16",
    "markdown-exec[ansi] >=1.11.0",
    "pydocstyle >=6.3.0",
    "linkcheckmd >=1.4.0",
    "mkdocs-external-images",
    "mkdocs-macros-plugin>=1.5.0",
    "flet-cli",
    { include-group = 'extensions' },
    { include-group = 'docs-coverage' },
]
all = [
    { include-group = 'dev' },
    { include-group = 'docs' },
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.uv.sources]
mkdocs-external-images = { git = "https://github.com/flet-dev/mkdocs-external-images", tag = "v0.2.0" }
