[tool.poetry]
name = "flet"
version = "0.1.0"
description = "Flet for Python - easily build interactive multi-platform apps in Python"
authors = ["Appveyor Systems Inc. <hello@flet.dev>"]
license = "Apache-2.0"
readme = "README.md"

packages = [{ include = "flet", from = "src" }]

[tool.poetry.urls]
homepage = "https://flet.dev"
repository = "https://github.com/flet-dev/flet"
documentation = "https://flet.dev/docs"

[tool.poetry.dependencies]
python = "^3.8"
flet-cli = { version = "0.1.0", optional = true }
flet-desktop = { version = "0.1.0", optional = true, markers = "platform_system == 'Darwin' or platform_system == 'Windows'" }
flet-web = { version = "0.1.0", optional = true }
oauthlib = { version = "^3.2.2", markers = "platform_system != 'Pyodide'" }
httpx = { version = "*", markers = "platform_system != 'Pyodide'" }
repath = "^0.9.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.6"
pytest = "^7.2.0"
cryptography = "^39.0.0"

[tool.poetry.extras]
all = ["flet-cli", "flet-desktop", "flet-web"]
cli = ["flet-cli"]
web = ["flet-web"]
desktop = ["flet-desktop"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
