[tool.poetry]
name = "flet"
version = "0.1.0"
description = "Flet for Python - easily build interactive multi-platform apps in Python"
authors = ["Appveyor Systems Inc. <hello@flet.dev>"]
license = "Apache-2.0"
readme = "README.md"

packages = [
    { include = "flet", from = "src" },
]

[tool.poetry.urls]
homepage = "https://flet.dev"
repository = "https://github.com/flet-dev/flet"
documentation = "https://flet.dev/docs"

[tool.poetry.dependencies]
flet-runtime = "0.1.0"
python = "^3.8"
typing-extensions = { version = "^4.6.2", python = "<3.8" }
websocket-client = "^1.5.2"
watchdog = "^3.0.0"
websockets = "^11.0.3"
packaging = "^23.1"
qrcode = "^7.4.2"
cookiecutter = "^2.4.0"
fastapi = "^0.109.2"
uvicorn = "^0.27.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.6"
pytest = "^7.2.0"
cryptography = "^39.0.0"

[tool.poetry.scripts]
flet = "flet.cli.cli:main"

[tool.poetry.plugins."pyinstaller40"]
hook-dirs = "flet.__pyinstaller:get_hook_dirs"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
float_to_top = true