name: flet_ads
description: Flet Ads control
homepage: https://flet.dev
repository: https://github.com/flet-dev/flet/packages/flet_ads
version: 0.25.2

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  google_mobile_ads: ^5.2.0

  flet:
    path: ../flet/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0